# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'homepage2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pathlib import Path
import sys
from create_event import EventCreatorApp
from displayeventuser import EventWindow as EventWindowUser
from displayeventhost import EventWindow as EventWindowHost
from backendfunctions import get_all_events, get_user_events,get_user_name_by_id,search_events


class Ui_MainWindow(QtWidgets.QMainWindow):
    def __init__(self, parent=None, user_id=None):
        super(QtWidgets.QMainWindow, self).__init__(parent)

        self.setObjectName("MainWindow")
        self.resize(984, 828)

        self.setStyleSheet(Path('signup.qss').read_text())

        self.createEventDialog = None
        self.user_id = user_id

        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")


        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(30, 20, 921, 761))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")

        self.layoutWidget = QtWidgets.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 50, 831, 50))
        self.layoutWidget.setObjectName("layoutWidget")

        self.searchHBox = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.searchHBox.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.searchHBox.setContentsMargins(20, 10, 10, 10)
        self.searchHBox.setSpacing(15)
        self.searchHBox.setObjectName("searchHBox")

        ##### search line
        self.searchLine = QtWidgets.QPlainTextEdit(self.layoutWidget)
        self.searchLine.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchLine.sizePolicy().hasHeightForWidth())
        self.searchLine.setSizePolicy(sizePolicy)
        self.searchLine.setMaximumSize(QtCore.QSize(770, 30))
        self.searchLine.setObjectName("searchLine")
        self.searchHBox.addWidget(self.searchLine)

        ##### search button
        self.searchButton = QtWidgets.QPushButton(self.layoutWidget)
        self.searchButton.setFixedSize(QtCore.QSize(90, 32))
        self.searchButton.setObjectName("searchButton")
        self.searchHBox.addWidget(self.searchButton)

        self.searchButton.clicked.connect(self.__getText)

        ##### create event button
        self.createEventButton = QtWidgets.QPushButton(self.frame)
        self.createEventButton.setGeometry(QtCore.QRect(340, 680, 221, 51))
        self.createEventButton.setObjectName("createEventButton")
        
        self.createEventButton.clicked.connect(self.__createEvent)


        ##### makes the events VBox scrollable
        self.scrollArea = QtWidgets.QScrollArea(self.frame)
        self.scrollArea.setGeometry(QtCore.QRect(50, 150, 831, 231))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setFixedSize(831, 231)
        self.scrollArea.setObjectName("scrollArea")

        ##### to be attached to the scroll area. Attach the widget that needs to 
        ##### scroll here.
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 812, 229))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")

        ##### events Vbox
        self.events = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.events.setContentsMargins(15, 15, 25, 15)
        self.events.setObjectName("events")
        
        ##### events box
        ##### creates the events and the detail

        self.eventsList = []


        self.eventBox1 = EventBox(False, {}, self.user_id)
    
       # self.events.addWidget(self.eventBox1)
        self.eventsList.append(self.eventBox1)

        self.eventBox2 = EventBox(False, {}, self.user_id)
        #self.events.addWidget(self.eventBox2)
        self.eventsList.append(self.eventBox2)

        self.eventBox3 = EventBox(False, {}, self.user_id)
        #self.events.addWidget(self.eventBox3)
        self.eventsList.append(self.eventBox3)

        ##### event boxes to the events widget
        for event in self.eventsList:
            self.events.addWidget(event)


        ##### refresh button for the user
        self.refreshButton = QtWidgets.QPushButton(self.frame)
        self.refreshButton.setGeometry(QtCore.QRect(800, 120, 75, 23))
        self.refreshButton.setObjectName("refreshButton")

        self.refreshButton.clicked.connect(self.load_events)



        ##### add the widget attached to the vbox to the scroll area.
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.scrollArea_2 = QtWidgets.QScrollArea(self.frame)
        self.scrollArea_2.setGeometry(QtCore.QRect(50, 420, 831, 231))
        self.scrollArea_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")

        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 812, 229))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        
        self.myEvents = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.myEvents.setContentsMargins(15, 15, 25, 15)
        self.myEvents.setSpacing(8)
        self.myEvents.setObjectName("myEvents")

        self.myEventsList = []

        self.myEvent1 = EventBox(True,{}, self.user_id)
        self.myEventsList.append(self.myEvent1)

        # my cycling event example
        self.myEvent2 = self.addEvent(EventBox(True,{},self.user_id))
        self.myEventsList.append(self.myEvent2)

        for event in self.myEventsList:
            self.myEvents.addWidget(event)

        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)

        ##### events label
        self.eventsLabel = QtWidgets.QLabel(self.frame)
        self.eventsLabel.setGeometry(QtCore.QRect(50, 35, 100, 200))
        self.eventsLabel.setObjectName("eventsLabel")

        ##### my events label
        self.myEventsLabel = QtWidgets.QLabel(self.frame)
        self.myEventsLabel.setGeometry(QtCore.QRect(50, 305, 100, 200))
        self.myEventsLabel.setObjectName("eventsLabel")

        ##### refresh button for the user's events
        self.refreshButtonUser = QtWidgets.QPushButton(self.frame)
        self.refreshButtonUser.setGeometry(QtCore.QRect(800, 390, 75, 23))
        self.refreshButtonUser.setObjectName("refreshButton")

        self.refreshButtonUser.clicked.connect(self.__load_user_events2) 

        
        self.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 984, 21))
        self.menubar.setObjectName("menubar")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

        
        #self.createEventDialog = None
        #self.user_id = user_id


        
        self.load_events()
        if self.user_id:
            self.load_user_events(self.user_id)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.searchLine.setPlaceholderText(_translate("MainWindow", "Search event..."))
        self.searchButton.setText(_translate("MainWindow", "Search"))
        self.createEventButton.setText(_translate("MainWindow", "CreateEvent"))
        self.myEventsLabel.setText(_translate("MainWindow", "My Events"))
        self.eventsLabel.setText(_translate("MainWindow", "Events"))
        self.refreshButton.setText(_translate("MainWindow", "Refresh"))
        self.refreshButtonUser.setText(_translate("MainWindow", "Refresh"))
        #self.eventBox.setTitle(_translate("MainWindow", "Event"))
        #self.label_3.setText(_translate("MainWindow", "TextLabel"))
        #self.label.setText(_translate("MainWindow", "TextLabel"))
        #self.label_4.setText(_translate("MainWindow", "TextLabel"))
        #self.label_5.setText(_translate("MainWindow", "TextLabel"))
        #self.eventBox_2.setTitle(_translate("MainWindow", "Event"))
        #self.label_11.setText(_translate("MainWindow", "TextLabel"))
        #self.label_2.setText(_translate("MainWindow", "TextLabel"))
        #self.label_12.setText(_translate("MainWindow", "TextLabel"))
        #self.label_13.setText(_translate("MainWindow", "TextLabel"))

    def __getText(self):
        text = self.searchLine.toPlainText()

        ### for developers
        print(text)
    
    #
    # adds the details of the events to the event box
    #  filled with test items for now.
    #
    def addEvent(self, eventBox: QtWidgets.QGroupBox):
        # Test event data
        event_data = {
            "Event Name": "Cycle Bowie",
            "DateTime": "some date and time format",
            "Sport": "Cycling",
            "Location": "Bowie, MD",
            "EventCreatorID": "dummy_id",  # Dummy creator ID
            "Description": "Fun cycling exercise around Bowie!"
        }

        eventBox.set_event_data(event_data, "James Jaluag")
        return eventBox

        
    def __createEvent(self):
        if self.createEventDialog is not None:
            self.createEventDialog.close()  # Close the existing dialog if any
        self.createEventDialog = EventCreatorApp(self.user_id, self)
        self.createEventDialog.show()
 

    
    def load_events(self):
        # Clear existing events in the list
        for i in reversed(range(self.events.count())):
            self.events.itemAt(i).widget().setParent(None)

        # Load all events from Firebase
        all_events = get_all_events()
        for event_data in all_events:
            event_creator_name = get_user_name_by_id(event_data["EventCreatorID"])
            is_owner = event_data["EventCreatorID"] == self.user_id
            event_box = EventBox(is_owner, event_data, self.user_id)
            event_box.set_event_data(event_data, event_creator_name)
            self.events.addWidget(event_box)


    def load_user_events(self, user_id):
        # Clear existing events in the myEvents list
        for i in reversed(range(self.myEvents.count())):
            self.myEvents.itemAt(i).widget().setParent(None)

        # Load user-specific events from Firebase
        user_events = get_user_events(user_id)
        for event_data in user_events:
            event_creator_name = get_user_name_by_id(event_data["EventCreatorID"])
            event_box = EventBox(True, event_data, self.user_id)  # Add user_id here
            event_box.set_event_data(event_data, event_creator_name)
            self.myEvents.addWidget(event_box)
    
    ###
    # private version of the load user events for the refresh button.
    # uses the global self.user_id instead of the argument style.
    ###
    def __load_user_events2(self):
        # Clear existing events in the myEvents list
        for i in reversed(range(self.myEvents.count())):
            self.myEvents.itemAt(i).widget().setParent(None)

        # Load user-specific events from Firebase
        user_events = get_user_events(self.user_id)
        for event_data in user_events:
            event_creator_name = get_user_name_by_id(event_data["EventCreatorID"])
            # Include self.user_id when initializing EventBox
            event_box = EventBox(True, event_data, self.user_id)
            event_box.set_event_data(event_data, event_creator_name)
            self.myEvents.addWidget(event_box)
            
    def __getText(self):
    # Get the text from the search box
        search_query = self.searchLine.toPlainText()

        # Use the search function from backendfunctions.py
        matching_events = search_events(search_query)

        # For simplicity, we will clear the events list and repopulate it with the search results.
        for i in reversed(range(self.events.count())):
            self.events.itemAt(i).widget().setParent(None)

        if matching_events:
            for event_data in matching_events:
                event_creator_name = get_user_name_by_id(event_data["EventCreatorID"])
                # Include self.user_id when initializing EventBox
                event_box = EventBox(False, event_data, self.user_id)
                event_box.set_event_data(event_data, event_creator_name)
                self.events.addWidget(event_box)
        else:
            print("No matching events found.")

        # For debugging
        print(f"Found {len(matching_events)} events for search query '{search_query}'")





    







############### EVENT BOX ###############
# creates event box with the event      #
#   details                             #
#                                       #
#                                       #
# NOTE: will add a class with all the   #
#         details                       #
#                                       #
#########################################

class EventBox(QtWidgets.QGroupBox):

    def __init__(self, is_owner, event_data, user_id, parent=None):
        super(EventBox, self).__init__(parent)
        self.is_owner = is_owner
        self.event_data = event_data if event_data else {}
        self.user_id = user_id 


        self.setFixedSize(QtCore.QSize(770, 125))
        self.setObjectName("eventBox")
       

        self.gridLayoutWidget = QtWidgets.QWidget(self)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 19, 771, 111))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayoutWidget.setContentsMargins(10,0,20,0)
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 15)
        self.gridLayout.setSpacing(15)
        self.gridLayout.setObjectName("gridLayout")

        self.dateTime = QtWidgets.QLabel(self.gridLayoutWidget)
        self.dateTime.setMaximumSize(QtCore.QSize(300, 30))
        self.dateTime.setObjectName("dateTime")
        self.gridLayout.addWidget(self.dateTime, 0, 2, 1, 1)
        
        self.eventTitle = QtWidgets.QLabel(self.gridLayoutWidget)
        self.eventTitle.setMaximumSize(QtCore.QSize(300, 30))
        self.eventTitle.setObjectName("eventTitle")
        self.gridLayout.addWidget(self.eventTitle, 0, 0, 1, 1)

        self.sport = QtWidgets.QLabel(self.gridLayoutWidget)
        self.sport.setMaximumSize(QtCore.QSize(300, 30))
        self.sport.setObjectName("sport")
        self.gridLayout.addWidget(self.sport, 0, 1, 1, 1)

        self.location = QtWidgets.QLabel(self.gridLayoutWidget)
        self.location.setMaximumSize(QtCore.QSize(300, 30))
        self.location.setObjectName("location")
        self.gridLayout.addWidget(self.location, 2, 1, 1, 1)

        self.host = QtWidgets.QLabel(self.gridLayoutWidget)
        self.host.setMaximumSize(QtCore.QSize(300, 30))
        self.host.setObjectName("host")
        self.gridLayout.addWidget(self.host, 2, 2, 1, 1)

        self.description = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.description.setMaximumSize(QtCore.QSize(300, 40))
        self.description.setReadOnly(True)
        self.description.setText("Add description here..")
        self.description.setObjectName("description")
        self.gridLayout.addWidget(self.description, 2, 0, 1, 1)

        self.detailsButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.detailsButton.setFixedSize(QtCore.QSize(120,30))
        self.detailsButton.setContentsMargins(0,10,150,10)
        self.detailsButton.clicked.connect(self.__detailsButton)
        self.gridLayout.addWidget(self.detailsButton, 0, 3, 1, 1)


        # translation for whatever idk what for
        # I think the setText or smthg
        _translate = QtCore.QCoreApplication.translate
        self.setTitle(_translate("MainWindow", "Event"))
        self.dateTime.setText(_translate("MainWindow", "Date and Time"))
        self.eventTitle.setText(_translate("MainWindow", "Event name"))
        self.location.setText(_translate("MainWindow", "Location"))
        self.host.setText(_translate("MainWindow", "Host"))
        self.sport.setText(_translate("MainWindow", "Sport"))
        self.detailsButton.setText(_translate("MainWindow", "Details"))

    ##
    # opens up the details of the 
    # event based on the user's ownership
    ##
    def __detailsButton(self):
        # if owner
            # If the user is the owner, open the event window for the host
            if self.is_owner:
                print("I'm the owner")
                event_window = EventWindowHost(self.event_data, self.user_id, self)
            # Otherwise, open the event window for a regular user
            else:
                print("Just a user")
                event_window = EventWindowUser(self.event_data, self.user_id,self)
            
            event_window.show()

    def set_event_data(self, event_data, event_creator_name):
        # Set the text for each UI element with data from event_data
        self.eventTitle.setText(event_data.get("Event Name", "Unknown Event"))
        self.dateTime.setText(event_data.get("DateTime", "Unknown Date/Time"))
        self.sport.setText(event_data.get("Sport", "Unknown Sport"))
        self.location.setText(event_data.get("Location", "Unknown Location"))
        self.host.setText(event_creator_name)  # Use the name instead of the ID
        self.description.setText(event_data.get("Description", "No description provided."))




########## Runs the window above #############
# NOTE: Do not forget to remove this when    #
#       integrating to the main proj         #
#                                            #
##############################################

if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    window = Ui_MainWindow()
    window.setWindowTitle("Stay Active Local")
    window.show()
    sys.exit(app.exec())
